# Use an official Python runtime as the base image
FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

# Update and install dependencies
RUN apt-get update && \
    apt-get install -y software-properties-common

# Install Python3
RUN apt-get install -y python3 python3-pip openjdk-8-jdk

RUN rm -rf /var/lib/apt/lists/*

# Set the working directory in the container
WORKDIR /app

# Copy the Python script files to the working directory
COPY . .

# Install the required Python packages
RUN pip3 install --no-cache-dir -r requirements.txt

# Set the command to run when the container starts
CMD ["python3", "part_2_b.py"]
